name: SonarCloud ESP-IDF Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: Build and Analyze
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compilar o projeto (Gera compile_commands.json)
        run: |
          /opt/esp/entrypoint.sh idf.py build

      - name: Executar análise do SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.organization=morustree
            -Dsonar.projectKey=morustree_Field-Station-ESP32-S3
            -Dsonar.sources=main
            -Dsonar.cfamily.compile-commands=build/compile_commands.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
